spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path= /auth/**, /tms/users/**, /
        - id: TASK-SERVICE
          uri: lb://TASK-SERVICE
          predicates:
            - Path= /tms/tasks/**
        - id: TASK-SUBMISSION
          uri: lb://TASK-SUBMISSION
          predicates:
            - Path= /tms/taskSubmission/**

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
